version: "3.7"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus:/data:rw
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: target

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: target
    volumes:
      - ./grafana:/var/lib/grafana:rw
