project:
  name: Ozon Code Platform Template API
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 7002
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

gateway:
  host: 0.0.0.0
  port: 7000
  allowedCorsOrigins:
    - "http://localhost:7001"
    - "http://0.0.0.0:7001"
    - "http://127.0.0.1:7001"

swagger:
  host: 0.0.0.0
  port: 7001
  filepath: "swagger/api/product-service/product-service.swagger.json"

categoryServiceAddr: "localhost:6002"
