version: "3.7"

services:
  postgres:
    image: postgres:latest
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: target
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
