project:
  name: Ozon Code Platform Template API
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8081

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

jaeger:
  service: "ocp-template-api"
  host: "jaeger"
  port: ":6831"

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: ocp_template_api
  sslmode: disable
  migrations: migrations
  driver: pgx

kafka:
  capacity: 512
  topic: "ocp-template-events"
  groupId: "ocp-template-api"
  brokers:
    - "kafka:9092"
    - "localhost:9094"
